In [129]:
import pandas as pd
import numpy as np

In [130]:
df = pd.read_csv("turkiye_kiralik_daireler.csv")
df.head()

                location                     information         sales_price
0     İstanbul - Beyoğlu    Daire | 1+1 | 4. Kat | 70 m²           17.000 TL
1       Ankara - Çankaya  Daire | 1 Oda | 3. Kat | 45 m²  25.000 TL29.000 TL
2        Samsun - Atakum   Daire | 2+1 | 3. Kat | 110 m²           23.000 TL
3           İzmir - Buca    Daire | 2+0 | 2. Kat | 75 m²           15.000 TL
4  İstanbul - Arnavutköy    Daire | 1+1 | 4. Kat | 70 m²           16.000 TL

information kolonunu parçalıyorum

In [131]:
df[["konut_tipi","oda_sayisi","kat","metrekare"]] = df["information"].str.split("|", expand = True).apply(lambda x : x.str.strip())

In [132]:
df.head()

,location,information,sales_price,konut_tipi,oda_sayisi,kat,metrekare
0,İstanbul - Beyoğlu,Daire | 1+1 | 4. Kat | 70 m²,17.000 TL,Daire,1+1,4. Kat,70 m²
1,Ankara - Çankaya,Daire | 1 Oda | 3. Kat | 45 m²,25.000 TL29.000 TL,Daire,1 Oda,3. Kat,45 m²
2,Samsun - Atakum,Daire | 2+1 | 3. Kat | 110 m²,23.000 TL,Daire,2+1,3. Kat,110 m²
3,İzmir - Buca,Daire | 2+0 | 2. Kat | 75 m²,15.000 TL,Daire,2+0,2. Kat,75 m²
4,İstanbul - Arnavutköy,Daire | 1+1 | 4. Kat | 70 m²,16.000 TL,Daire,1+1,4. Kat,70 m²

birden fazla veri olan information kolonunu siliyorum. Artık "konut_tipi","oda_sayisi","kat","metrekare" var

In [133]:
df.drop("information", axis=1, inplace=True)

kat kolonundaki . ları sildim

In [134]:
df["kat"] = df["kat"].str.replace(".", "", regex=False)

kat kolonundaki Kat kelimesini sildim

In [135]:
df["kat"] = df["kat"].str.replace("Kat", "", regex=False).str.strip()

In [136]:
df.head()

,location,sales_price,konut_tipi,oda_sayisi,kat,metrekare
0,İstanbul - Beyoğlu,17.000 TL,Daire,1+1,4,70 m²
1,Ankara - Çankaya,25.000 TL29.000 TL,Daire,1 Oda,3,45 m²
2,Samsun - Atakum,23.000 TL,Daire,2+1,3,110 m²
3,İzmir - Buca,15.000 TL,Daire,2+0,2,75 m²
4,İstanbul - Arnavutköy,16.000 TL,Daire,1+1,4,70 m²

In [137]:
df["metrekare"] = df["metrekare"].str.replace("m²", "", regex=False).str.strip()
df.head()

,location,sales_price,konut_tipi,oda_sayisi,kat,metrekare
0,İstanbul - Beyoğlu,17.000 TL,Daire,1+1,4,70
1,Ankara - Çankaya,25.000 TL29.000 TL,Daire,1 Oda,3,45
2,Samsun - Atakum,23.000 TL,Daire,2+1,3,110
3,İzmir - Buca,15.000 TL,Daire,2+0,2,75
4,İstanbul - Arnavutköy,16.000 TL,Daire,1+1,4,70

In [138]:
df["sales_price"] = df["sales_price"].str.replace("TL", "", regex=False)
df["sales_price"] = df["sales_price"].str.replace(".", "", regex=False)
df["sales_price"] = df["sales_price"].str.strip()

df.head()

                location  sales_price konut_tipi oda_sayisi kat metrekare
0     İstanbul - Beyoğlu        17000      Daire        1+1   4        70
1       Ankara - Çankaya  25000 29000      Daire      1 Oda   3        45
2        Samsun - Atakum        23000      Daire        2+1   3       110
3           İzmir - Buca        15000      Daire        2+0   2        75
4  İstanbul - Arnavutköy        16000      Daire        1+1   4        70

In [139]:
df.rename(columns={"sales_price" : "fiyat"}, inplace=True)
df.head()

                location        fiyat konut_tipi oda_sayisi kat metrekare
0     İstanbul - Beyoğlu        17000      Daire        1+1   4        70
1       Ankara - Çankaya  25000 29000      Daire      1 Oda   3        45
2        Samsun - Atakum        23000      Daire        2+1   3       110
3           İzmir - Buca        15000      Daire        2+0   2        75
4  İstanbul - Arnavutköy        16000      Daire        1+1   4        70

In [141]:
df[["il","ilce"]] = df["location"].str.split(" - ",expand=True)
df.drop(columns=['location'], inplace=True)
df.head()

         fiyat konut_tipi oda_sayisi kat metrekare        il        ilce
0        17000      Daire        1+1   4        70  İstanbul     Beyoğlu
1  25000 29000      Daire      1 Oda   3        45    Ankara     Çankaya
2        23000      Daire        2+1   3       110    Samsun      Atakum
3        15000      Daire        2+0   2        75     İzmir        Buca
4        16000      Daire        1+1   4        70  İstanbul  Arnavutköy

In [ ]:
# df["mahalle"] = df["mahalle"].astype(str)
# df["mahalle"] = df["mahalle"].str.replace("Mahallesi", "").str.strip()

In [142]:
new_sort = ["konut_tipi","oda_sayisi","kat","metrekare","il","ilce","fiyat"]
df = df[new_sort]
df

,konut_tipi,oda_sayisi,kat,metrekare,il,ilce,fiyat
0,Daire,1+1,4,70,İstanbul,Beyoğlu,17000
1,Daire,1 Oda,3,45,Ankara,Çankaya,25000 29000
2,Daire,2+1,3,110,Samsun,Atakum,23000
3,Daire,2+0,2,75,İzmir,Buca,15000
4,Daire,1+1,4,70,İstanbul,Arnavutköy,16000
...,...,...,...,...,...,...,...
1495,Daire,3+1,8,147,İstanbul,Küçükçekmece,50500
1496,Daire,2+1,Yüksek giriş,77,Kocaeli,İzmit,23000 25000
1497,Daire,2+1,3,110,İstanbul,Esenyurt,15000
1498,Daire,3+1,3,128,İstanbul,Esenyurt,25000
1499,Daire,4+1,5,170,Antalya,Finike,37000

In [143]:
df["il"].dtype

dtype('O')

In [144]:
df["il"] = df["il"].astype("string")
df["ilce"] = df["ilce"].astype("string")
df["konut_tipi"] = df["konut_tipi"].astype("string")

In [145]:
df.head()

  konut_tipi oda_sayisi kat metrekare        il        ilce        fiyat
0      Daire        1+1   4        70  İstanbul     Beyoğlu        17000
1      Daire      1 Oda   3        45    Ankara     Çankaya  25000 29000
2      Daire        2+1   3       110    Samsun      Atakum        23000
3      Daire        2+0   2        75     İzmir        Buca        15000
4      Daire        1+1   4        70  İstanbul  Arnavutköy        16000

### Sorunlar

In [148]:
df["oda_sayisi"].unique()

array(['1+1', '1 Oda', '2+1', '2+0', '3+1', '4+1', 'Stüdyo', '2+2',
       '3.5+1', '5+1', '5+2', '3+2', '1.5+1', '2.5+1', '4+2', '3+0',
       '6+1'], dtype=object)

In [147]:
df[df["oda_sayisi"] == "1 Oda"]

,konut_tipi,oda_sayisi,kat,metrekare,il,ilce,fiyat
1,Daire,1 Oda,3,45,Ankara,Çankaya,25000 29000
7,Daire,1 Oda,2,55,Muğla,Bodrum,35000
81,Daire,1 Oda,2,45,Adana,Seyhan,9500
161,Daire,1 Oda,3,60,Batman,Batman Merkez,16000
326,Daire,1 Oda,Yüksek giriş,35,Ankara,Etimesgut,14000
334,Daire,1 Oda,Yüksek giriş,35,Ankara,Etimesgut,14000
400,Daire,1 Oda,3,45,Adana,Seyhan,9500
404,Daire,1 Oda,3,55,Eskişehir,Tepebaşı,10000
409,Daire,1 Oda,2,30,Gaziantep,Şahinbey,8000
925,Daire,1 Oda,Kot 2 (-2),40,İstanbul,Şişli,16000
1090,Daire,1 Oda,Çatı katı,70,Denizli,Pamukkale,8000

In [146]:
df["il"].unique()

<StringArray>
[      'İstanbul',         'Ankara',         'Samsun',          'İzmir',
          'Hatay',          'Muğla',         'Edirne',          'Adana',
       'Tekirdağ',      'Eskişehir',       'Kırşehir',        'Denizli',
     'Diyarbakır',         'Mersin',        'Kocaeli',         'Manisa',
        'Antalya',        'Isparta',          'Niğde',      'Balıkesir',
     'Kırklareli',          'Aydın',           'Bolu',        'Sakarya',
          'Bursa',      'Kastamonu',          'Tokat',         'Batman',
         'Yalova',        'Trabzon',        'Kayseri',          'Konya',
      'Gaziantep',         'Elazığ', 'Afyonkarahisar',       'Nevşehir',
      'Zonguldak',        'Karabük',        'Giresun',        'Karaman',
      'Çanakkale',      'Şanlıurfa',            'Van',         'Yozgat',
           'Ordu',          'Kilis',           'Rize',        'Malatya',
         'Mardin',          'Düzce',          'Sivas',         'Burdur',
           'KKTC',  'Kahramanmaraş',           'Kars',      'Kırıkkale',
         'Bartın',        'Erzurum',         'Amasya',       'Erzincan',
        'Kütahya',       'Osmaniye']
Length: 62, dtype: string

konut tipi olarak yalnızca daire var

In [ ]:
df["konut_tipi"].unique()

sayısal olmayan kat verileri var

In [ ]:
df["kat"].unique()

sadece merkez ilçesi var

In [ ]:
df["ilce"].unique()

In [ ]:
df[df["ilce"].str.strip().str.lower() != "merkez"]

In [ ]:
df.head()

In [ ]:
df["mahalle"] = df["mahalle"].str.strip("[]").str.strip()

In [ ]:
df.head()

In [152]:
df.to_csv("data_kira.csv", index=False)