In [82]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np

2- 7 sayfalardaki verileri çekiyor.

In [85]:
page = 2
all_data = []

def data_scraping(tag:str, attr:str ,attr_value:str) -> np.array:
    data_list = []
    if attr == "class_":
        data = soup.find_all(f"{tag}", class_ = f"{attr_value}")
    for i in data:
        data_list.append(i.get_text())
    return data_list


while page < 8:
    url = f"https://www.emlakjet.com/kiralik-daire/duzce?sayfa={page}"
    print(f"Sayfa {page} -> {url}")

    response = requests.get(url)
    soup = BeautifulSoup(response.content, "html")

   
    
    st2 = soup.find_all("div", attrs= {"styles_listingWrapper__I0H_l"})
    if not st2: # veri gelmediyse duracak
        break


    locations = data_scraping("span", "class_","styles_location__ieVpH")
    # explanations = data_scraping("h3", "class_","styles_title__CN_n3")
    informations = data_scraping("div", "class_" ,"styles_quickinfoWrapper__F5BBD")
    sales_prices = data_scraping("div", "class_", "styles_priceContent__TBOLV")
    
    # her sayfayı ekler
    for loc, info, price in zip(locations, informations, sales_prices):
        all_data.append({
        "location": loc,
        "information": info,
        "sales_price": price
    })


    page += 1

url = f"https://www.emlakjet.com/kiralik-daire/duzce"
response = requests.get(url)
soup = BeautifulSoup(response.content, "html")
st2 = soup.find_all("div", attrs= {"styles_listingWrapper__I0H_l"})
df1 = pd.DataFrame(all_data)
df1.head()

Sayfa 2 -> https://www.emlakjet.com/kiralik-daire/duzce?sayfa=2
Sayfa 3 -> https://www.emlakjet.com/kiralik-daire/duzce?sayfa=3
Sayfa 4 -> https://www.emlakjet.com/kiralik-daire/duzce?sayfa=4
Sayfa 5 -> https://www.emlakjet.com/kiralik-daire/duzce?sayfa=5
Sayfa 6 -> https://www.emlakjet.com/kiralik-daire/duzce?sayfa=6
Sayfa 7 -> https://www.emlakjet.com/kiralik-daire/duzce?sayfa=7

,location,information,sales_price
0,Düzce Merkez - Aziziye Mahallesi,Daire | 3+1 | 3. Kat | 135 m²,20.500 TL
1,Düzce Merkez - Şehit Bayram Gökmen Mahallesi,Daire | 1 Oda | Kot 4 (-4). Kat | 60 m²,15.000 TL
2,Düzce Merkez - Şehit Murat Demir Mahallesi,Daire | 1+1 | 2. Kat | 70 m²,9.500 TL
3,Düzce Merkez - Şehit Murat Demir Mahallesi,Daire | 1+1 | Yüksek giriş | 55 m²,10.000 TL
4,Düzce Merkez - Güzelbahçe Mahallesi,Daire | 3+1 | Düz Giriş (Zemin) | 115 m²,14.000 TL

ilk sayfa eksikti onuda çektim

In [86]:
page1_data = []
url = f"https://www.emlakjet.com/kiralik-daire/duzce"
response = requests.get(url)
soup = BeautifulSoup(response.content, "html")

st2 = soup.find_all("div", attrs= {"styles_listingWrapper__I0H_l"})

locations = data_scraping("span", "class_","styles_location__ieVpH")
informations = data_scraping("div", "class_" ,"styles_quickinfoWrapper__F5BBD")
sales_prices = data_scraping("div", "class_", "styles_priceContent__TBOLV")

# her sayfayı ekler
for loc, info, price in zip(locations, informations, sales_prices):
    page1_data.append({
    "location": loc,
    "information": info,
    "sales_price": price
})
df2 = pd.DataFrame(page1_data)
df2.head()

,location,information,sales_price
0,Düzce Merkez - Şehit Murat Demir Mahallesi,Daire | 1+1 | Düz Giriş (Zemin) | 74 m²,9.500 TL
1,Düzce Merkez - Orhangazi Mahallesi,Daire | 1+1 | Yüksek giriş | 50 m²,11.000 TL
2,Düzce Merkez - Aziziye Mahallesi,Daire | 2+1 | 1. Kat | 170 m²,12.500 TL
3,Düzce Merkez - Orhangazi Mahallesi,Daire | 1+1 | 1. Kat | 60 m²,10.500 TL
4,Düzce Merkez - Orhangazi Mahallesi,Daire | 2+1 | 3. Kat | 70 m²,17.000 TL

In [88]:
df = pd.concat([df1, df2], ignore_index= True)
df

,location,information,sales_price
0,Düzce Merkez - Aziziye Mahallesi,Daire | 3+1 | 3. Kat | 135 m²,20.500 TL
1,Düzce Merkez - Şehit Bayram Gökmen Mahallesi,Daire | 1 Oda | Kot 4 (-4). Kat | 60 m²,15.000 TL
2,Düzce Merkez - Şehit Murat Demir Mahallesi,Daire | 1+1 | 2. Kat | 70 m²,9.500 TL
3,Düzce Merkez - Şehit Murat Demir Mahallesi,Daire | 1+1 | Yüksek giriş | 55 m²,10.000 TL
4,Düzce Merkez - Güzelbahçe Mahallesi,Daire | 3+1 | Düz Giriş (Zemin) | 115 m²,14.000 TL
...,...,...,...
190,Düzce Merkez - Orhangazi Mahallesi,Daire | 1+1 | 1. Kat | 62 m²,12.000 TL
191,Düzce Merkez - Fevziçakmak Mahallesi,Daire | 3+1 | 2. Kat | 130 m²,19.000 TL
192,Düzce Merkez - Camikebir Mahallesi,Daire | 2+1 | 3. Kat | 95 m²,15.000 TL
193,Düzce Merkez - Aziziye Mahallesi,Daire | 2+1 | 3. Kat | 100 m²,18.000 TL
194,Düzce Merkez - Çay Mahallesi,Daire | 3+1 | Yüksek giriş | 130 m²,17.500 TL

In [89]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   location     195 non-null    object
 1   information  195 non-null    object
 2   sales_price  195 non-null    object
dtypes: object(3)
memory usage: 4.7+ KB